---
# This file contains generic Linux system configuration tasks

- name: assert | os | assert required inputs
  tags: assert,ufw
  ansible.builtin.import_tasks: assertions/assert.yml
  run_once: yes
  delegate_to: localhost


- name: system | systemctl | set swappiness 
  tags: system,systemctl,swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ systemctl.swappiness }}"
    state: present
  when:
    - systemctl is defined
    - systemctl.swappiness is defined
