
- name: system | os | store hardware architecture
  ansible.builtin.command:
    cmd: uname -m
  register: uname_m

- name: system | os | store kernel name
  ansible.builtin.command:
    cmd: uname -s
  register: uname_s
