# This files contains configurations related to Ubuntu's unattended upgrades

- name: system | os | install 'unattended-upgrades'
  ansible.builtin.apt:
    name: unattended-upgrades
    state: latest

- name: system | os | enable 'unattended-upgrades'
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: 'true'

# This will apply any configured selections (the one right above) plus any default values.
- name: system | os | apply selections
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgrades
