---

# Load distribution specific variables (see ../base/vars/)
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  #
  #  Standalone utilities installation steps
  #
  - ansible.builtin.import_tasks: utilities.yml

  #
  #  OS agnostic system configuration
  #
  - ansible.builtin.import_tasks: system/main.yml

  #
  #  User configuration
  #
  - ansible.builtin.import_tasks: users/main.yml


  #
  # Root account configuration
  #
  # Deliberatly last since all previous steps need to 
  # have succeeded before, to avoid system lockout 
  #
  #- ansible.builtin.import_tasks: users/root.yml