---

- name: system | ufw | assert config schema
  ansible.utils.validate:
    data: "{{ ufw }}"
    criteria:
      - "{{ lookup('file',  './criteria/ufw-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  when:
  - ufw is defined