---
# Main execution file for base level software configurations

# perform system related configuration
- ansible.builtin.import_tasks: os/main.yml

# perform APT configuration
- ansible.builtin.import_tasks: apt.yml

# perform OpenSSH configuration
- ansible.builtin.import_tasks: openssh.yml

# performs ufw based firewall configuration
- ansible.builtin.import_tasks: ufw/main.yml
